### ISSUE TITLE
Another error:  syntax error where there should be no error

### ISSUE THREAD

**Issue by JKoltsov** [redivis/help#15] opened 2018-07-17 19:48 UTC
Alright, I switched over to my inpatient data build--again same code I ran 2 days ago, just switched out the medicare for the non-medicare Truven data.  I have a simple filter step filtering where dx1-dx3 != a list of exclusions, and I got the following error:

Syntax error: Unexpected "," at [8:18692]

Ian, I shared the project with you again--"Cervical Inpatient Surgery MEDICARE".

**Comment by imathews** [comment] 2018-07-19 00:53
@JKoltsov is this still occurring? I took a look at your project and didn't see any errored nodes. Feel free to point us towards the transform causing the error and we can investigate further

**Comment by JKoltsov** [comment] 2018-07-19 21:34
Yes, I still have the error on the "Apply exclusions dx1-dx3" transform (2nd one down) on the Cervical Inpatient Surgery MEDICARE project.

**Comment by imathews** [comment] 2018-07-19 21:55
@JKoltsov confirmed, will take a look

**Comment by JKoltsov** [comment] 2018-07-24 18:54
@imathews It seems to have something to do with having the two lists on the right hand side of the equation.  i.e. dx1 != list1, list2  does not work (both in filtering or if I enter something like this in a case statement to create a boolean variable).  I got the transform to work by using multiple lines in the filter:
dx1 != list 1 and
dx1 != list 2 and
dx2 != list 1 and
dx2 != list2 and
dx3 != list1 and
dx3 != list2

I also discovered in this process that having multiple variables on the left hand side is only supported for "=" and "and", not for "!="  (you probably already knew this, but I just realized it).

**Comment by imathews** [comment] 2018-07-24 20:59
@JKoltsov yes we just diagnosed this a couple hours ago — thanks for the find. The issue is as you describe; queries that have multiple right-hand lists aren't being formatted properly, causing a syntax error.

We've implemented a fix for this, we're just running some tests and wrapping up #14 — I'm also on a plane right now, but hope to have everything deployed this evening. Will follow up here once this is live.

**Comment by imathews** [comment] 2018-07-24 21:07
And yea, currently multiple left-hand inputs are supported only for the `=` and `like` operators, and compile to a logical OR (e.g., `diag1 = list OR diag2 = list`). For the others, I believe we would want a logical AND; for example:

`dx1, dx2 != list1` => `dx1 != list AND dx2 != list`

Is this consistent with your use case? We'll want to think about the UI here to avoid confusion, but I could imagine this being useful in certain circumstances.

cc @erindelaney

**Comment by JKoltsov** [comment] 2018-07-24 21:13
Thanks, Ian!  Yes, that is consistent with my use case and makes sense.

**Comment by imathews** [comment] 2018-07-25 06:15
@JKoltsov the primary bug here, where multiple lists in the right-hand side of a comparison was causing syntax errors, has been resolved. Keep us posted if you run into any other issues

**Closed by imathews** 2018-07-25 06:15 UTC

**Comment by JKoltsov** [comment] 2018-07-25 20:20
Great, thanks!
